name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install musl-tools
      run: sudo apt-get install musl-tools
    - name: Install libssl dependencies
      run: sudo apt-get install pkg-config libssl-dev
    - name: Install x86_64-unknown-linux-musl
      run: rustup target add x86_64-unknown-linux-musl
    - name: Build x86_64-unknown-linux-musl
      run: cargo build --release --target x86_64-unknown-linux-musl
    - name: Run tests
      run: cargo test --verbose
    - name: Install mingw-w64
      run: sudo apt-get install mingw-w64
    - name: Install x86_64-pc-windows-gnu target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build x86_64-pc-windows-gnu
      run: cargo build --release --target x86_64-pc-windows-gnu
    - name: Upload a Build Artifacts
      uses: actions/upload-artifact@v2.2.3
      with:
        name: target
        path: |
          target
    - name: Cache
      uses: actions/cache@v2.1.5
      with:
        path: |
          target
        key: target
      
